# Generated by Django 4.2.7 on 2025-11-11 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Имя и фамилия могут содержать только буквы, пробелы и дефис.', regex='^[a-zA-Zа-яА-ЯёЁ\\- ]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Имя и фамилия могут содержать только буквы, пробелы и дефис.', regex='^[a-zA-Zа-яА-ЯёЁ\\- ]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+7xxxxxxxxxx'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
