# Generated by Django 4.2.7 on 2025-11-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Максимальная скорость'),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Техническое состояние'),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач'),
        ),
    ]
